# Generated by Django 2.2 on 2019-04-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_auto_20161020_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
